const SAVE_PLACE = 'SAVE_PLACE'
const SAVE_PLACE_SUCCESS = 'SAVE_PLACE_SUCCESS'
const REMOVE_PLACE = 'REMOVE_PLACE'
const REMOVE_PLACE_SUCCESS = 'REMOVE_PLACE_SUCCESS'

export {
    SAVE_PLACE,
    SAVE_PLACE_SUCCESS,
    REMOVE_PLACE,
    REMOVE_PLACE_SUCCESS
}